# Compare imputation methods

# Load functions
source("../project_support.R")

# Find overall NRMSE per condition
overall_MCAR_10 <- overall_nrmse(condition = "MCAR_10")
overall_MCAR_20 <- overall_nrmse(condition = "MCAR_20")
overall_MCAR_30 <- overall_nrmse(condition = "MCAR_30")
overall_MCAR_40 <- overall_nrmse(condition = "MCAR_40")
overall_MCAR_50 <- overall_nrmse(condition = "MCAR_50")
overall_MCAR_60 <- overall_nrmse(condition = "MCAR_60")
overall_MCAR_70 <- overall_nrmse(condition = "MCAR_70")
overall_MCAR_80 <- overall_nrmse(condition = "MCAR_80")
overall_MAR_10 <- overall_nrmse(condition = "MAR_10")
overall_MAR_20 <- overall_nrmse(condition = "MAR_20")
overall_MAR_30 <- overall_nrmse(condition = "MAR_30")
overall_MAR_40 <- overall_nrmse(condition = "MAR_40")
overall_MAR_50 <- overall_nrmse(condition = "MAR_50")
overall_MAR_60 <- overall_nrmse(condition = "MAR_60")
overall_MAR_70 <- overall_nrmse(condition = "MAR_70")
overall_MAR_80 <- overall_nrmse(condition = "MAR_80")
overall_MCAR_10 <- overall_nrmse(condition = "MCAR_10")
overall_MCAR_20 <- overall_nrmse(condition = "MCAR_20")
overall_MCAR_30 <- overall_nrmse(condition = "MCAR_30")
overall_MCAR_40 <- overall_nrmse(condition = "MCAR_40")
overall_MCAR_50 <- overall_nrmse(condition = "MCAR_50")
overall_MCAR_60 <- overall_nrmse(condition = "MCAR_60")
overall_MCAR_70 <- overall_nrmse(condition = "MCAR_70")
overall_MCAR_80 <- overall_nrmse(condition = "MCAR_80")

# Find NRMSE foe each variable per condition
var_MCAR_10 <- variable_nrmse(condition = "MCAR_10")
var_MCAR_20 <- variable_nrmse(condition = "MCAR_20")
var_MCAR_30 <- variable_nrmse(condition = "MCAR_30")
var_MCAR_40 <- variable_nrmse(condition = "MCAR_40")
var_MCAR_50 <- variable_nrmse(condition = "MCAR_50")
var_MCAR_60 <- variable_nrmse(condition = "MCAR_60")
var_MCAR_70 <- variable_nrmse(condition = "MCAR_70")
var_MCAR_80 <- variable_nrmse(condition = "MCAR_80")
var_MAR_10 <- variable_nrmse(condition = "MAR_10")
var_MAR_20 <- variable_nrmse(condition = "MAR_20")
var_MAR_30 <- variable_nrmse(condition = "MAR_30")
var_MAR_40 <- variable_nrmse(condition = "MAR_40")
var_MAR_50 <- variable_nrmse(condition = "MAR_50")
var_MAR_60 <- variable_nrmse(condition = "MAR_60")
var_MAR_70 <- variable_nrmse(condition = "MAR_70")
var_MAR_80 <- variable_nrmse(condition = "MAR_80")
var_MNAR_10 <- variable_nrmse(condition = "MNAR_10")
var_MNAR_20 <- variable_nrmse(condition = "MNAR_20")
var_MNAR_30 <- variable_nrmse(condition = "MNAR_30")
var_MNAR_40 <- variable_nrmse(condition = "MNAR_40")
var_MNAR_50 <- variable_nrmse(condition = "MNAR_50")
var_MNAR_60 <- variable_nrmse(condition = "MNAR_60")
var_MNAR_70 <- variable_nrmse(condition = "MNAR_70")
var_MNAR_80 <- variable_nrmse(condition = "MNAR_80")
